version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inexcons_app
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/var/www/backend
    depends_on:
      - database
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_URL: http://localhost:8080
      LOG_CHANNEL: stderr

  database:
    image: postgres:14
    container_name: inexcons_db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
